"""End-to-end tests with synthetic Banksalad data.

This test suite validates the complete pipeline workflow using synthetic
transaction data that mimics Banksalad exports. It measures performance,
accuracy, and generates comprehensive reports.

The synthetic data is generated by scripts/generate_e2e_fixtures.py and includes:
- Transactions matching sample_rules.yaml patterns (cafes, convenience stores, etc.)
- Transfer pairs for pairing algorithm testing
- Untagged merchants for rule effectiveness analysis
- 3 months of data for partition testing

Tests:
1. Clean pipeline run with synthetic data
2. Incremental update (idempotency)
3. Performance benchmarks
4. Rule effectiveness analysis
5. Transfer detection accuracy
6. Report generation and validation
"""

import shutil
from datetime import datetime
from pathlib import Path

import pytest

from finjuice.pipeline.export.master import export_master_xlsx
from finjuice.pipeline.export.reports import generate_all_reports
from finjuice.pipeline.ingest.pipeline import ingest_all_files, ingest_file
from finjuice.pipeline.storage import csv_partition
from finjuice.pipeline.tagging.pipeline import run_tagging
from finjuice.pipeline.transfer.detection import run_transfer_detection

# Test data paths - using synthetic data for reproducible CI testing
SYNTHETIC_DATA_SOURCE = Path("tests/fixtures/e2e/synthetic_banksalad_e2e.xlsx")
SAMPLE_RULES = Path("tests/fixtures/sample_rules.yaml")


@pytest.fixture
def real_data_dir(tmp_path: Path) -> Path:
    """Create a temporary data directory with synthetic test data.

    Args:
        tmp_path: pytest temporary directory

    Returns:
        Path to test data directory with structure:
        - imports/synthetic_banksalad_e2e.xlsx
        - transactions/ (CSV partitions)
        - rules.yaml
        - exports/
        - exports/reports/
    """
    # Create directory structure
    data_dir = tmp_path / "data"
    imports_dir = data_dir / "imports"
    csv_base_dir = data_dir / "transactions"
    exports_dir = data_dir / "exports"
    reports_dir = exports_dir / "reports"

    imports_dir.mkdir(parents=True)
    csv_base_dir.mkdir(parents=True)
    reports_dir.mkdir(parents=True)

    # Copy synthetic test data
    if not SYNTHETIC_DATA_SOURCE.exists():
        pytest.skip(
            f"Synthetic data not found: {SYNTHETIC_DATA_SOURCE}. "
            "Run 'uv run python scripts/generate_e2e_fixtures.py' to generate."
        )

    shutil.copy(SYNTHETIC_DATA_SOURCE, imports_dir / SYNTHETIC_DATA_SOURCE.name)

    # Copy sample rules
    if not SAMPLE_RULES.exists():
        pytest.skip(f"Sample rules not found: {SAMPLE_RULES}")

    shutil.copy(SAMPLE_RULES, data_dir / "rules.yaml")

    return data_dir


@pytest.mark.e2e
def test_clean_pipeline_with_real_data(real_data_dir: Path) -> None:
    """Test complete pipeline run with real anonymized data.

    Validates:
    - All phases complete successfully
    - Tag coverage meets >60% target
    - Transfer pairs are detected
    - All reports are generated
    """
    # Setup paths
    csv_base_dir = real_data_dir / "transactions"
    imports_dir = real_data_dir / "imports"
    rules_path = real_data_dir / "rules.yaml"
    exports_dir = real_data_dir / "exports"
    reports_dir = exports_dir / "reports"

    # Phase 1: Ingest
    ingest_summary = ingest_all_files(imports_dir, csv_base_dir)
    assert ingest_summary["files"] > 0, "No files ingested"
    assert ingest_summary["inserted"] > 0, "No transactions inserted"

    # Phase 2: Tag
    tag_summary = run_tagging(csv_base_dir, rules_path)
    assert tag_summary["total"] > 0, "No transactions to tag"
    assert tag_summary["tagged"] > 0, "No transactions were tagged"

    # Phase 3: Transfer Detection
    transfer_summary = run_transfer_detection(csv_base_dir)
    assert transfer_summary["candidates"] >= 0, "Invalid transfer candidate count"

    # Phase 4: Export
    today = datetime.now().strftime("%Y%m%d")
    master_path = exports_dir / f"master_{today}.xlsx"
    row_count = export_master_xlsx(csv_base_dir, master_path)
    reports_summary = generate_all_reports(csv_base_dir, reports_dir)

    assert master_path.exists(), "Master XLSX not created"
    assert row_count > 0, "Master XLSX is empty"
    assert reports_summary["reports"] == 5, "Not all reports generated"


@pytest.mark.e2e
def test_synthetic_fixture_edge_cases(real_data_dir: Path) -> None:
    """The synthetic fixture must exercise every edge-case class on ingest.

    Guards issue #699: the E2E fixture always carries duplicate rows, transfer
    pairs, malformed rows, and tagging edge cases, so the suite keeps testing
    deduplication, row-level validation, transfer detection, and rule coverage.
    """
    csv_base_dir = real_data_dir / "transactions"
    imports_dir = real_data_dir / "imports"
    rules_path = real_data_dir / "rules.yaml"
    xlsx_path = imports_dir / SYNTHETIC_DATA_SOURCE.name

    inserted, skipped_dedup, skipped_rows = ingest_file(xlsx_path, csv_base_dir)

    # Duplicate rows are deduplicated by row_hash on ingest.
    assert skipped_dedup >= 3, f"expected >=3 deduplicated rows, got {skipped_dedup}"
    # Malformed rows are skipped row-by-row without aborting the file.
    assert len(skipped_rows) >= 3, f"expected >=3 skipped malformed rows, got {skipped_rows}"
    assert inserted > 0, "no valid transactions ingested"

    # Tagging edge cases: both tagged and untagged transactions are present.
    tag_summary = run_tagging(csv_base_dir, rules_path)
    assert tag_summary["tagged"] > 0, "no tagged transactions"
    assert tag_summary["tagged"] < tag_summary["total"], "expected some untagged transactions"

    # Transfer pairs are detected.
    transfer_summary = run_transfer_detection(csv_base_dir)
    assert transfer_summary["pairs"] > 0, "no transfer pairs detected"


@pytest.mark.e2e
def test_incremental_update(real_data_dir: Path) -> None:
    """Test incremental pipeline run (idempotency).

    Validates:
    - Running pipeline twice produces identical results
    - No duplicate transactions created
    - Tags remain consistent
    - Transfer pairs remain consistent
    """
    csv_base_dir = real_data_dir / "transactions"
    imports_dir = real_data_dir / "imports"
    rules_path = real_data_dir / "rules.yaml"

    # First run
    ingest_all_files(imports_dir, csv_base_dir)
    run_tagging(csv_base_dir, rules_path)
    run_transfer_detection(csv_base_dir)

    # Collect first run state (Polars)
    df1 = csv_partition.get_all_transactions(csv_base_dir)
    count1 = len(df1)
    hashes1 = set(df1["row_hash"].to_list())
    tags1 = {row["row_hash"]: row["tags_final"] for row in df1.iter_rows(named=True)}

    # Second run (should be idempotent)
    ingest_all_files(imports_dir, csv_base_dir)
    run_tagging(csv_base_dir, rules_path)
    run_transfer_detection(csv_base_dir)

    # Collect second run state (Polars)
    df2 = csv_partition.get_all_transactions(csv_base_dir)
    count2 = len(df2)
    hashes2 = set(df2["row_hash"].to_list())
    tags2 = {row["row_hash"]: row["tags_final"] for row in df2.iter_rows(named=True)}

    # Validate idempotency
    assert count1 == count2, f"Transaction count changed: {count1} → {count2}"
    assert hashes1 == hashes2, "Row hashes differ between runs"
    assert tags1 == tags2, "Tags differ between runs"


@pytest.mark.e2e
@pytest.mark.slow
def test_performance_benchmarks(real_data_dir: Path) -> None:
    """Test pipeline performance benchmarks.

    Validates:
    - Total execution time stays within the documented perf baseline
      (``tests/e2e/perf_baseline.json``), not just a very high wall-clock cap.
    - All phases complete successfully
    """
    import time

    from tests.e2e.metrics import load_performance_budget

    csv_base_dir = real_data_dir / "transactions"
    imports_dir = real_data_dir / "imports"
    rules_path = real_data_dir / "rules.yaml"
    exports_dir = real_data_dir / "exports"
    reports_dir = exports_dir / "reports"

    # Run full pipeline with timing
    start_time = time.time()

    ingest_all_files(imports_dir, csv_base_dir)
    run_tagging(csv_base_dir, rules_path)
    run_transfer_detection(csv_base_dir)

    today = datetime.now().strftime("%Y%m%d")
    master_path = exports_dir / f"master_{today}.xlsx"
    export_master_xlsx(csv_base_dir, master_path)
    generate_all_reports(csv_base_dir, reports_dir)

    total_time = time.time() - start_time

    # Validate against the reviewed perf baseline, not an arbitrary high cap.
    budget = load_performance_budget()
    assert total_time < budget, (
        f"Execution time {total_time:.2f}s exceeds the documented {budget:.0f}s "
        "budget for the synthetic E2E pipeline (see tests/e2e/perf_baseline.json)"
    )

    # Validate outputs exist
    assert master_path.exists(), "Master XLSX not created"
    df = csv_partition.get_all_transactions(csv_base_dir)
    assert len(df) > 0, "No transactions in CSV"


@pytest.mark.e2e
def test_rule_effectiveness(real_data_dir: Path) -> None:
    """Test rule effectiveness and tag coverage.

    Validates:
    - Tag coverage meets >60% target
    - Rules match expected merchants
    - Untagged merchants are identified
    """
    csv_base_dir = real_data_dir / "transactions"
    imports_dir = real_data_dir / "imports"
    rules_path = real_data_dir / "rules.yaml"

    # Run ingest and tagging
    ingest_all_files(imports_dir, csv_base_dir)
    tag_summary = run_tagging(csv_base_dir, rules_path)

    # Validate tag coverage
    # Note: With real data + test rules, coverage may be low
    # In production, target is >60% with proper rules
    # For E2E, we just verify tagging works
    assert tag_summary["tagged"] > 0, "No transactions were tagged"

    # Get untagged merchants (Polars)
    import polars as pl

    df = csv_partition.get_all_transactions(csv_base_dir)
    # Filter for empty tags_final (Polars List type)
    # tags_final is stored as List[str] - use .list.len() for empty check
    untagged_df = df.filter(
        (pl.col("tags_final").list.len() == 0) | (pl.col("tags_final").is_null())
    )

    if len(untagged_df) > 0:
        merchant_counts = (
            untagged_df.group_by("merchant_raw")
            .agg(pl.len().alias("count"))
            .sort("count", descending=True)
            .head(10)
        )

        # Report untagged merchants (informational)
        print("\n🏷️  Top untagged merchants:")
        for row in merchant_counts.iter_rows(named=True):
            print(f"  - {row['merchant_raw']}: {row['count']} transactions")


@pytest.mark.e2e
def test_transfer_detection_accuracy(real_data_dir: Path) -> None:
    """Test transfer detection accuracy.

    Validates:
    - Transfer pairs are detected
    - is_transfer flag is set correctly
    - transfer_group_id is assigned
    - Unpaired transfers remain unpaired
    """
    csv_base_dir = real_data_dir / "transactions"
    imports_dir = real_data_dir / "imports"
    rules_path = real_data_dir / "rules.yaml"

    # Run pipeline through transfer detection
    ingest_all_files(imports_dir, csv_base_dir)
    run_tagging(csv_base_dir, rules_path)
    transfer_summary = run_transfer_detection(csv_base_dir)

    # Get transfer pairs (Polars)
    import polars as pl

    df = csv_partition.get_all_transactions(csv_base_dir)
    paired_df = df.filter(
        (pl.col("is_transfer") == 1) & (pl.col("transfer_group_id").is_not_null())
    )

    # Group by transfer_group_id and count
    group_counts = paired_df.group_by("transfer_group_id").agg(pl.len().alias("count"))

    # Validate all pairs have exactly 2 transactions
    for row in group_counts.iter_rows(named=True):
        group_id = row["transfer_group_id"]
        count = row["count"]
        assert count == 2, f"Transfer group {group_id} has {count} transactions (expected 2)"

    # Validate is_transfer flag
    # Note: "candidates" is all transactions with type='이체'
    # "is_transfer=1" are those actually processed/marked as transfers
    # These counts may differ (candidates >= is_transfer)
    transfer_count = len(df.filter(pl.col("is_transfer") == 1))

    # Just validate some transfers were marked
    assert transfer_count > 0, "No transactions marked as transfers"
    assert transfer_count <= transfer_summary["candidates"], (
        "More is_transfer than candidates - data integrity issue"
    )

    # Check for unpaired transfers
    # Note: "unpaired" in summary = candidates that weren't matched (candidates - paired)
    # They may or may not have is_transfer=1 set
    # We just verify that paired count matches what's in the CSV partitions.
    paired_in_partitions = len(df.filter(pl.col("transfer_group_id").is_not_null()))

    assert paired_in_partitions == transfer_summary["paired"], (
        "Paired count mismatch: "
        f"partitions have {paired_in_partitions}, summary says {transfer_summary['paired']}"
    )


@pytest.mark.e2e
def test_report_generation_and_validation(real_data_dir: Path) -> None:
    """Test report generation and content validation.

    Validates:
    - All CSV reports are generated
    - Master XLSX has all required columns
    - Reports have correct structure
    - Transfer exclusion works (no transfers in expense reports)
    """
    csv_base_dir = real_data_dir / "transactions"
    imports_dir = real_data_dir / "imports"
    rules_path = real_data_dir / "rules.yaml"
    exports_dir = real_data_dir / "exports"
    reports_dir = exports_dir / "reports"

    # Run full pipeline
    ingest_all_files(imports_dir, csv_base_dir)
    run_tagging(csv_base_dir, rules_path)
    run_transfer_detection(csv_base_dir)

    # Export reports
    today = datetime.now().strftime("%Y%m%d")
    master_path = exports_dir / f"master_{today}.xlsx"
    row_count = export_master_xlsx(csv_base_dir, master_path)
    reports_summary = generate_all_reports(csv_base_dir, reports_dir)

    # Validate master XLSX
    assert master_path.exists(), "Master XLSX not created"
    assert row_count > 0, "Master XLSX is empty"

    # Validate all 5 reports exist
    assert reports_summary["reports"] == 5, "Not all reports generated"

    expected_reports = [
        "monthly_spend.csv",
        "by_tag.csv",
        "by_account.csv",
        "transfers.csv",
    ]

    for report_name in expected_reports:
        report_path = reports_dir / report_name
        assert report_path.exists(), f"Report {report_name} not found"
        assert report_path.stat().st_size > 0, f"Report {report_name} is empty"


@pytest.mark.skip(
    reason="Real data file may contain pre-existing duplicates - deduplication tested in unit tests"
)
@pytest.mark.e2e
def test_csv_partition_consistency(real_data_dir: Path) -> None:
    """Test data consistency and integrity.

    Validates:
    - No duplicate row_hash values
    - All required fields are populated
    - Tags are valid Python lists
    """
    csv_base_dir = real_data_dir / "transactions"
    imports_dir = real_data_dir / "imports"

    # Run ingestion
    ingest_all_files(imports_dir, csv_base_dir)

    # Get all transactions
    df = csv_partition.get_all_transactions(csv_base_dir)

    # Check for duplicate row hashes
    duplicate_hashes = df[df["row_hash"].duplicated()]["row_hash"].tolist()
    assert len(duplicate_hashes) == 0, f"Found {len(duplicate_hashes)} duplicate row_hash values"

    # Check required fields
    null_dates = df["date"].isna().sum()
    assert null_dates == 0, "Found transactions with NULL date"

    null_amounts = df["amount"].isna().sum()
    assert null_amounts == 0, "Found transactions with NULL amount"

    # Validate tags_final are lists
    for idx, tags in enumerate(df["tags_final"]):
        assert isinstance(tags, list), f"Row {idx}: tags_final is not a list: {type(tags)}"
