"""
Markdown report generation (Issue #117).

This module generates GitHub-friendly Markdown reports with:
- Summary statistics
- Monthly spending table
- Tag breakdown table
- Top merchants table
"""

import html
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

try:
    import polars as pl

    POLARS_AVAILABLE = True
except ImportError:
    POLARS_AVAILABLE = False
    pl = None  # type: ignore[assignment]  # optional dep fallback; guarded before use


def _check_dependencies() -> None:
    """Check if required dependencies are available."""
    missing = []
    if not POLARS_AVAILABLE:
        missing.append("polars")

    if missing:
        raise ImportError(
            f"Missing required dependencies: {', '.join(missing)}. "
            f"Install with: uv sync --extra templates"
        )


def _format_currency(amount: float | int) -> str:
    """Format a numeric amount as KRW."""
    return f"₩{abs(amount):,.0f}"


def _escape_markdown_cell(value: object) -> str:
    """Escape user-controlled text for a GitHub-flavored Markdown table cell."""
    escaped = html.escape(str(value), quote=True)
    escaped = escaped.replace("|", "\\|")
    return escaped.replace("\r\n", "<br>").replace("\n", "<br>").replace("\r", "<br>")


def _render_markdown_table(headers: list[str], rows: list[list[str]], align_right: set[int]) -> str:
    """Render a GitHub-flavored Markdown table."""
    separator = ["---:" if index in align_right else "---" for index in range(len(headers))]
    lines = [
        f"| {' | '.join(headers)} |",
        f"| {' | '.join(separator)} |",
    ]
    for row in rows:
        lines.append(f"| {' | '.join(row)} |")
    return "\n".join(lines)


def _render_markdown_report(
    summary: dict,
    monthly_spend_rows: list[dict],
    tag_breakdown_rows: list[dict],
    top_merchants_rows: list[dict],
) -> str:
    """Render Markdown without requiring Jinja2."""
    monthly_rows = [
        [
            _escape_markdown_cell(row["month"]),
            f"{row['transaction_count']}건",
            _format_currency(row["total_amount"]),
        ]
        for row in monthly_spend_rows
    ]
    tag_rows = [
        [
            _escape_markdown_cell(row["tag"]),
            f"{row['transaction_count']}건",
            _format_currency(row["total_amount"]),
            f"{abs(row['percentage']):.1f}%",
        ]
        for row in tag_breakdown_rows
    ]
    merchant_rows = [
        [
            str(index),
            _escape_markdown_cell(row["merchant"]),
            f"{row['transaction_count']}건",
            _format_currency(row["total_amount"]),
        ]
        for index, row in enumerate(top_merchants_rows, 1)
    ]

    sections = [
        "# 💰 재무 분석 리포트",
        "",
        f"**기간**: {_escape_markdown_cell(summary['period'])}",
        f"**생성일**: {_escape_markdown_cell(summary['generated_at'])}",
        "",
        "---",
        "",
        "## 📊 요약",
        "",
        _render_markdown_table(
            ["항목", "값"],
            [
                ["총 거래 건수", f"{summary['total_transactions']:,}건"],
                ["총 지출", _format_currency(summary["total_expenses"])],
                ["총 수입", _format_currency(summary["total_income"])],
            ],
            {1},
        ),
        "",
        "---",
        "",
        "## 📈 월별 지출 추이",
        "",
        _render_markdown_table(["월", "거래 건수", "총 지출"], monthly_rows, {1, 2}),
        "",
        "---",
        "",
        "## 🏷️ 태그별 지출 분포",
        "",
        _render_markdown_table(["태그", "거래 건수", "총 지출", "비율"], tag_rows, {1, 2, 3}),
        "",
        "---",
        "",
        f"## 🏪 주요 가맹점 (Top {len(top_merchants_rows)})",
        "",
        _render_markdown_table(
            ["순위", "가맹점", "거래 건수", "총 지출"],
            merchant_rows,
            {0, 2, 3},
        ),
        "",
        "---",
        "",
        "*Generated by [finjuice](https://github.com/sungjunlee/finjuice) - Local-first Personal Finance Tools*",
    ]

    return "\n".join(sections)


def generate_markdown_report(
    csv_base_dir: Path,
    output_path: Path,
    period: Optional[str] = None,
    source_df: "pl.DataFrame | None" = None,
) -> Path:
    """
    Generate GitHub-friendly Markdown report.

    Args:
        csv_base_dir: Base directory for CSV partitions
        output_path: Path to output Markdown file
        period: Optional period filter (YYYY-MM format)

    Returns:
        Path to generated Markdown file

    Raises:
        ImportError: If required dependencies are not installed
        RuntimeError: If report generation fails
    """
    _check_dependencies()

    from finjuice.pipeline.export.aggregations import (
        calculate_monthly_spend,
        calculate_summary_stats,
        calculate_tag_breakdown,
        calculate_top_merchants,
        load_transactions,
    )

    logger.info("Generating Markdown report")

    try:
        # Load and process data
        df = load_transactions(csv_base_dir, period, source_df=source_df)
        monthly_spend = calculate_monthly_spend(df)
        tag_breakdown = calculate_tag_breakdown(df, top_n=10)
        top_merchants = calculate_top_merchants(df, limit=20)
        summary = calculate_summary_stats(df, period)

        monthly_spend_rows = monthly_spend.to_dicts()
        tag_breakdown_rows = tag_breakdown.to_dicts()
        top_merchants_rows = top_merchants.to_dicts()

        md_content = _render_markdown_report(
            summary,
            monthly_spend_rows,
            tag_breakdown_rows,
            top_merchants_rows,
        )

        # Write to file
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(md_content, encoding="utf-8")

        logger.info("Markdown report generated")
        return output_path

    except (OSError, ValueError, pl.exceptions.PolarsError) as e:
        logger.error("Failed to generate Markdown report (%s)", type(e).__name__)
        raise RuntimeError(f"Markdown report generation failed: {e}") from e
