"""Workspace registry persistence and symlink layout helpers.

Owns the on-disk workspace contract: workspaces.yaml registry I/O, identity
checks, symlink create/verify, and the workspace README template. Typer
commands stay in :mod:`finjuice.pipeline.cli.commands.workspace_cmd`.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

import yaml

# Workspace metadata version
WORKSPACE_VERSION = 1

# Symlink targets
SYMLINK_TARGETS = ["imports", "exports", "transactions"]
FILE_SYMLINKS = ["rules.yaml"]

WORKSPACE_README_TEMPLATE = """# Finance Workspace

This is a finjuice workspace directory. All directories here are symlinks
to your actual data stored in the OS-specific data location.

## Structure

- `imports/` → Import XLSX files here
- `exports/` → Generated reports and master files
- `transactions/` → CSV partition storage (read-only recommended)
- `rules.yaml` → Tagging rules configuration

## Usage

```bash
# Run full pipeline
finjuice refresh

# Check status
finjuice status

# Edit tagging rules
vim rules.yaml
finjuice tag
```

## Data Location

Your actual data is stored at the path specified in `.finjuice-workspace`.

## Warning

Do NOT delete this workspace if you have uncommitted changes.
Removing this workspace does NOT delete your actual data.

---
Generated by finjuice workspace create
"""


def load_workspace_registry(data_dir: Path) -> dict[str, Any]:
    """Load workspace registry from data directory."""
    registry_file = data_dir / "metadata" / "workspaces.yaml"
    if registry_file.exists():
        return yaml.safe_load(registry_file.read_text()) or {"workspaces": []}
    return {"workspaces": []}


def save_workspace_registry(data_dir: Path, registry: dict[str, Any]) -> None:
    """Save workspace registry to data directory."""
    metadata_dir = data_dir / "metadata"
    metadata_dir.mkdir(parents=True, exist_ok=True)
    registry_file = metadata_dir / "workspaces.yaml"
    registry_file.write_text(yaml.dump(registry, default_flow_style=False))


def register_workspace(data_dir: Path, workspace_path: Path) -> None:
    """Register workspace in global registry."""
    registry = load_workspace_registry(data_dir)
    workspaces = registry.get("workspaces", [])

    # Check if already registered
    existing_paths = [w.get("path") for w in workspaces]
    if str(workspace_path) not in existing_paths:
        workspaces.append(
            {
                "path": str(workspace_path),
                "created_at": datetime.now().isoformat(),
            }
        )
        registry["workspaces"] = workspaces
        save_workspace_registry(data_dir, registry)


def unregister_workspace(data_dir: Path, workspace_path: Path) -> None:
    """Unregister workspace from global registry."""
    registry = load_workspace_registry(data_dir)
    workspaces = registry.get("workspaces", [])

    # Remove matching workspace
    workspaces = [w for w in workspaces if w.get("path") != str(workspace_path)]
    registry["workspaces"] = workspaces
    save_workspace_registry(data_dir, registry)


def is_valid_workspace(workspace_path: Path) -> bool:
    """Check if directory is a valid workspace."""
    metadata_file = workspace_path / ".finjuice-workspace"
    return metadata_file.exists()


def validate_data_directories(data_dir: Path) -> list[str]:
    """Validate that required data directories exist. Returns list of missing."""
    missing = []
    for target in SYMLINK_TARGETS:
        if not (data_dir / target).exists():
            missing.append(target)
    for target in FILE_SYMLINKS:
        if not (data_dir / target).exists():
            missing.append(target)
    return missing


def create_symlinks(workspace_path: Path, data_dir: Path) -> None:
    """Create symlinks from workspace to data directory."""
    for target in SYMLINK_TARGETS:
        link = workspace_path / target
        source = data_dir / target
        link.symlink_to(source)

    for target in FILE_SYMLINKS:
        link = workspace_path / target
        source = data_dir / target
        link.symlink_to(source)


def verify_symlinks(workspace_path: Path) -> list[tuple[str, str]]:
    """Verify all symlinks are valid. Returns list of (name, status)."""
    results = []
    all_targets = SYMLINK_TARGETS + FILE_SYMLINKS

    for target in all_targets:
        link = workspace_path / target
        if not link.exists():
            if link.is_symlink():
                results.append((target, "broken"))
            else:
                results.append((target, "missing"))
        elif link.is_symlink():
            results.append((target, "valid"))
        else:
            results.append((target, "not_symlink"))

    return results
