"""
Workspace command: Manage symlink-based work directories.

Provides user-friendly workspace creation for easy data access,
especially useful for Claude Code and other AI tools (Issue #65).
"""

import logging
import shutil
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Annotated, Optional

import typer
import yaml

from finjuice.pipeline.cli.output import console, error, success, warning

logger = logging.getLogger(__name__)

# Workspace metadata version
WORKSPACE_VERSION = 1

# Symlink targets
SYMLINK_TARGETS = ["imports", "exports", "transactions"]
FILE_SYMLINKS = ["rules.yaml"]

workspace_app = typer.Typer(help="Manage workspace directories (symlink-based)")

WORKSPACE_README_TEMPLATE = """# Finance Workspace

This is a finjuice workspace directory. All directories here are symlinks
to your actual data stored in the OS-specific data location.

## Structure

- `imports/` → Import XLSX files here
- `exports/` → Generated reports and master files
- `transactions/` → CSV partition storage (read-only recommended)
- `rules.yaml` → Tagging rules configuration

## Usage

```bash
# Run full pipeline
finjuice refresh

# Check status
finjuice status

# Edit tagging rules
vim rules.yaml
finjuice tag
```

## Data Location

Your actual data is stored at the path specified in `.finjuice-workspace`.

## Warning

Do NOT delete this workspace if you have uncommitted changes.
Removing this workspace does NOT delete your actual data.

---
Generated by finjuice workspace create
"""


def get_open_command() -> str:
    """Get platform-specific command to open files/directories."""
    import platform

    system = platform.system()
    if system == "Darwin":
        return "open"
    elif system == "Linux":
        return "xdg-open"
    elif system == "Windows":
        return "explorer"
    else:
        raise NotImplementedError(f"Unsupported platform: {system}")


def load_workspace_registry(data_dir: Path) -> dict:
    """Load workspace registry from data directory."""
    registry_file = data_dir / "metadata" / "workspaces.yaml"
    if registry_file.exists():
        return yaml.safe_load(registry_file.read_text()) or {"workspaces": []}
    return {"workspaces": []}


def save_workspace_registry(data_dir: Path, registry: dict) -> None:
    """Save workspace registry to data directory."""
    metadata_dir = data_dir / "metadata"
    metadata_dir.mkdir(parents=True, exist_ok=True)
    registry_file = metadata_dir / "workspaces.yaml"
    registry_file.write_text(yaml.dump(registry, default_flow_style=False))


def register_workspace(data_dir: Path, workspace_path: Path) -> None:
    """Register workspace in global registry."""
    registry = load_workspace_registry(data_dir)
    workspaces = registry.get("workspaces", [])

    # Check if already registered
    existing_paths = [w.get("path") for w in workspaces]
    if str(workspace_path) not in existing_paths:
        workspaces.append(
            {
                "path": str(workspace_path),
                "created_at": datetime.now().isoformat(),
            }
        )
        registry["workspaces"] = workspaces
        save_workspace_registry(data_dir, registry)


def unregister_workspace(data_dir: Path, workspace_path: Path) -> None:
    """Unregister workspace from global registry."""
    registry = load_workspace_registry(data_dir)
    workspaces = registry.get("workspaces", [])

    # Remove matching workspace
    workspaces = [w for w in workspaces if w.get("path") != str(workspace_path)]
    registry["workspaces"] = workspaces
    save_workspace_registry(data_dir, registry)


def is_valid_workspace(workspace_path: Path) -> bool:
    """Check if directory is a valid workspace."""
    metadata_file = workspace_path / ".finjuice-workspace"
    return metadata_file.exists()


def validate_data_directories(data_dir: Path) -> list[str]:
    """Validate that required data directories exist. Returns list of missing."""
    missing = []
    for target in SYMLINK_TARGETS:
        if not (data_dir / target).exists():
            missing.append(target)
    for target in FILE_SYMLINKS:
        if not (data_dir / target).exists():
            missing.append(target)
    return missing


def create_symlinks(workspace_path: Path, data_dir: Path) -> None:
    """Create symlinks from workspace to data directory."""
    for target in SYMLINK_TARGETS:
        link = workspace_path / target
        source = data_dir / target
        link.symlink_to(source)

    for target in FILE_SYMLINKS:
        link = workspace_path / target
        source = data_dir / target
        link.symlink_to(source)


def verify_symlinks(workspace_path: Path) -> list[tuple[str, str]]:
    """Verify all symlinks are valid. Returns list of (name, status)."""
    results = []
    all_targets = SYMLINK_TARGETS + FILE_SYMLINKS

    for target in all_targets:
        link = workspace_path / target
        if not link.exists():
            if link.is_symlink():
                results.append((target, "broken"))
            else:
                results.append((target, "missing"))
        elif link.is_symlink():
            results.append((target, "valid"))
        else:
            results.append((target, "not_symlink"))

    return results


@workspace_app.command("create")
def workspace_create(
    ctx: typer.Context,
    path: Annotated[
        Path,
        typer.Argument(help="Path to create workspace"),
    ],
) -> None:
    """
    Create a new workspace directory with symlinks.

    Creates a workspace with symlinks to the data directory, making it
    easy to access your finance data from convenient locations.

    Examples:
        # Create workspace in Documents
        finjuice workspace create ~/Documents/my-finance

        # Create workspace on Desktop
        finjuice workspace create ~/Desktop/finance-review
    """
    from finjuice.pipeline.config import Config, validate_not_program_repo_path

    # Get config from context
    config: Optional[Config] = None
    if ctx.obj and "config" in ctx.obj:
        config = ctx.obj["config"]

    if config is None:
        console.print("Configuration not initialized", style="red")
        raise typer.Exit(code=1)

    data_dir = config.data_dir
    workspace_path = path.expanduser().resolve()
    try:
        validate_not_program_repo_path(workspace_path, context="workspace directory")
    except ValueError as exc:
        console.print(str(exc), style="red")
        raise typer.Exit(code=1) from exc

    # Validate data directories exist
    missing = validate_data_directories(data_dir)
    if missing:
        console.print(
            f"Data directories not found: {', '.join(missing)}",
            style="red",
        )
        console.print("\nRun 'finjuice init' to create required directories")
        raise typer.Exit(code=1)

    # Check workspace doesn't already exist with content
    if workspace_path.exists():
        if any(workspace_path.iterdir()):
            console.print(
                f"Directory already exists and is not empty: {workspace_path}",
                style="red",
            )
            raise typer.Exit(code=1)
    else:
        workspace_path.mkdir(parents=True)

    # Create symlinks
    try:
        create_symlinks(workspace_path, data_dir)
    except OSError as e:
        console.print(f"Failed to create symlinks: {e}", style="red")
        raise typer.Exit(code=1)

    # Write metadata
    metadata = {
        "version": WORKSPACE_VERSION,
        "data_dir": str(data_dir),
        "created_at": datetime.now().isoformat(),
    }
    metadata_file = workspace_path / ".finjuice-workspace"
    metadata_file.write_text(yaml.dump(metadata, default_flow_style=False))

    # Write README
    readme_file = workspace_path / "README.md"
    readme_file.write_text(WORKSPACE_README_TEMPLATE)

    # Register workspace
    register_workspace(data_dir, workspace_path)

    # Success message
    console.print()
    success(f"Created workspace: {workspace_path}")
    console.print()
    console.print("📁 Structure:")
    for target in SYMLINK_TARGETS:
        console.print(f"   {target}/ → {data_dir / target}")
    for target in FILE_SYMLINKS:
        console.print(f"   {target} → {data_dir / target}")

    console.print(f"\n💡 Now you can work from {workspace_path}")
    console.print("\n📋 Next steps:")
    console.print(f"   cd {workspace_path}")
    console.print("   ls -la imports/")
    console.print("   finjuice refresh")


@workspace_app.command("list")
def workspace_list(
    ctx: typer.Context,
) -> None:
    """
    List all active workspaces.

    Shows all workspaces that have been created and their status.
    """
    from finjuice.pipeline.config import Config

    # Get config from context
    config: Optional[Config] = None
    if ctx.obj and "config" in ctx.obj:
        config = ctx.obj["config"]

    if config is None:
        console.print("Configuration not initialized", style="red")
        raise typer.Exit(code=1)

    data_dir = config.data_dir
    registry = load_workspace_registry(data_dir)
    workspaces = registry.get("workspaces", [])

    if not workspaces:
        console.print("\n📁 No workspaces found\n")
        console.print("Create one with: finjuice workspace create <path>")
        return

    console.print("\n📁 Active workspaces:\n", style="bold")
    for i, ws in enumerate(workspaces, 1):
        ws_path = Path(ws.get("path", ""))
        created = ws.get("created_at", "Unknown")

        # Check if still valid
        if ws_path.exists() and is_valid_workspace(ws_path):
            status = "✅ Valid"
        else:
            status = "❌ Invalid/Missing"

        console.print(f"   {i}. {ws_path}")
        console.print(f"      Created: {created}")
        console.print(f"      Status: {status}\n")

    console.print(f"💾 Data location: {data_dir}")


@workspace_app.command("remove")
def workspace_remove(
    ctx: typer.Context,
    path: Annotated[
        Path,
        typer.Argument(help="Workspace path to remove"),
    ],
    force: Annotated[
        bool,
        typer.Option("--force", "-f", help="Skip confirmation"),
    ] = False,
    yes: Annotated[
        bool,
        typer.Option("--yes", "-y", help="Skip confirmation"),
    ] = False,
) -> None:
    """
    Remove a workspace directory (data remains safe).

    Removes the workspace directory and symlinks but does NOT delete
    your actual data.
    """
    from finjuice.pipeline.config import Config

    # Get config from context
    config: Optional[Config] = None
    if ctx.obj and "config" in ctx.obj:
        config = ctx.obj["config"]

    if config is None:
        console.print("Configuration not initialized", style="red")
        raise typer.Exit(code=1)

    data_dir = config.data_dir
    workspace_path = path.expanduser().resolve()

    # Check workspace exists
    if not workspace_path.exists():
        console.print(f"Workspace not found: {workspace_path}", style="red")
        raise typer.Exit(code=1)

    # Check it's a valid workspace
    if not is_valid_workspace(workspace_path):
        console.print(
            f"Not a valid workspace (missing .finjuice-workspace): {workspace_path}",
            style="red",
        )
        raise typer.Exit(code=1)

    # Confirm removal
    if not force and not yes:
        console.print()
        warning("This will remove the workspace directory and symlinks.")
        console.print("   Your actual data will NOT be deleted.\n")
        confirm = typer.confirm("Proceed?")
        if not confirm:
            console.print("Cancelled")
            raise typer.Exit(code=0)

    # Remove workspace
    try:
        shutil.rmtree(workspace_path)
    except OSError as e:
        console.print(f"Failed to remove workspace: {e}", style="red")
        raise typer.Exit(code=1)

    # Unregister
    unregister_workspace(data_dir, workspace_path)

    console.print()
    success(f"Removed workspace: {workspace_path}")
    console.print(f"💾 Data remains safe at: {data_dir}")


@workspace_app.command("verify")
def workspace_verify(
    ctx: typer.Context,
    path: Annotated[
        Path,
        typer.Argument(help="Workspace path to verify"),
    ],
) -> None:
    """
    Verify workspace symlinks are valid.

    Checks that all symlinks in the workspace point to valid targets.
    """
    workspace_path = path.expanduser().resolve()

    # Check workspace exists
    if not workspace_path.exists():
        console.print(f"Workspace not found: {workspace_path}", style="red")
        raise typer.Exit(code=1)

    # Check it's a valid workspace
    if not is_valid_workspace(workspace_path):
        console.print(
            f"Not a valid workspace (missing .finjuice-workspace): {workspace_path}",
            style="red",
        )
        raise typer.Exit(code=1)

    console.print(f"\n🔍 Verifying workspace: {workspace_path}\n")

    # Verify symlinks
    results = verify_symlinks(workspace_path)
    all_valid = True

    for name, status in results:
        if status == "valid":
            success(f"{name} → Valid symlink")
        elif status == "broken":
            error(f"{name} → Broken symlink")
            all_valid = False
        elif status == "missing":
            error(f"{name} → Missing")
            all_valid = False
        else:
            warning(f"{name} → Not a symlink")
            all_valid = False

    # Check metadata
    metadata_file = workspace_path / ".finjuice-workspace"
    if metadata_file.exists():
        success(".finjuice-workspace → Valid metadata")
    else:
        error(".finjuice-workspace → Missing")
        all_valid = False

    console.print()
    if all_valid:
        success("All checks passed!")
    else:
        error("Some checks failed")
        raise typer.Exit(code=1)


@workspace_app.command("open")
def workspace_open(
    ctx: typer.Context,
    path: Annotated[
        Path,
        typer.Argument(help="Workspace path to open"),
    ],
) -> None:
    """
    Open workspace in file manager.

    Opens the workspace directory in your system's file manager
    (Finder on macOS, Explorer on Windows, etc.).
    """
    workspace_path = path.expanduser().resolve()

    # Check workspace exists
    if not workspace_path.exists():
        console.print(f"Workspace not found: {workspace_path}", style="red")
        raise typer.Exit(code=1)

    # Check it's a valid workspace
    if not is_valid_workspace(workspace_path):
        console.print(
            f"Not a valid workspace (missing .finjuice-workspace): {workspace_path}",
            style="red",
        )
        raise typer.Exit(code=1)

    # Open in file manager
    try:
        from finjuice.pipeline.constants import SUBPROCESS_TIMEOUT_SHORT

        command = get_open_command()
        subprocess.run([command, str(workspace_path)], timeout=SUBPROCESS_TIMEOUT_SHORT)
        console.print(f"Opened: {workspace_path}")
    except Exception as e:  # intended catch-all for CLI robustness
        console.print(f"Failed to open: {e}", style="red")
        raise typer.Exit(code=1)


def register_workspace_command(app: typer.Typer) -> None:
    """Register the workspace command group with the Typer app."""
    app.add_typer(workspace_app, name="workspace", rich_help_panel="Admin")
