"""Tests for package artifact content verification."""

from __future__ import annotations

import warnings
import zipfile
from pathlib import Path

import pytest

from scripts import check_package_contents


def test_expected_wheel_paths_are_derived_from_runtime_resource_sources(tmp_path: Path) -> None:
    """Expected wheel resources should follow the source package and schema trees."""
    (tmp_path / "src/finjuice/templates/sql").mkdir(parents=True)
    (tmp_path / "schemas").mkdir()
    (tmp_path / "src/finjuice/templates/schema.yaml").write_text("schema", encoding="utf-8")
    (tmp_path / "src/finjuice/templates/sql/registry.yaml").write_text(
        "queries: []", encoding="utf-8"
    )
    (tmp_path / "schemas/status.schema.json").write_text("{}", encoding="utf-8")

    assert check_package_contents.expected_wheel_resource_paths(tmp_path) == [
        "finjuice/schemas/status.schema.json",
        "finjuice/templates/schema.yaml",
        "finjuice/templates/sql/registry.yaml",
    ]


def test_expected_wheel_paths_ignore_generated_bytecode(tmp_path: Path) -> None:
    """Generated bytecode in the checkout should not become an expected package resource."""
    (tmp_path / "src/finjuice/templates/__pycache__").mkdir(parents=True)
    (tmp_path / "schemas").mkdir()
    (tmp_path / "src/finjuice/templates/schema.yaml").write_text("schema", encoding="utf-8")
    (tmp_path / "src/finjuice/templates/__pycache__/__init__.cpython-313.pyc").write_bytes(b"pyc")
    (tmp_path / "schemas/status.schema.json").write_text("{}", encoding="utf-8")

    assert check_package_contents.expected_wheel_resource_paths(tmp_path) == [
        "finjuice/schemas/status.schema.json",
        "finjuice/templates/schema.yaml",
    ]


def test_archive_check_rejects_duplicate_resource_entries(tmp_path: Path) -> None:
    """Duplicate entries in a wheel should fail even if the resource exists."""
    wheel_path = tmp_path / "finjuice-0.0.0-py3-none-any.whl"
    expected_path = "finjuice/templates/schema.yaml"

    with zipfile.ZipFile(wheel_path, "w") as wheel:
        wheel.writestr(expected_path, "first")
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            wheel.writestr(expected_path, "second")

    with pytest.raises(check_package_contents.PackageContentError, match="more than once"):
        check_package_contents.check_paths_once(
            archive_name=wheel_path.name,
            members=check_package_contents.zip_members(wheel_path),
            expected_paths=[expected_path],
        )
